name: Build
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['11', '17']
        os: [ubuntu-latest]
    steps:

    - name: Check out repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    # Install Java.
    - name: Set up JDK
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
        cache: maven

    - name: Build
      run: |
        ./mvnw clean package
        echo ${{ matrix.java_version }}
